language: python

python:
  - "2.7"

env:
  - DJANGO="Django>=1.11.0"

install:
  - pip install -q $DJANGO
  - pip install coveralls

script:
  - coverage run runtests.py

after_success:
  - coveralls
